schema: "classroom50/repo-config/v1"
classroom: "ufjf-dcc202-2026-3-b"
assignment: "atv05"
assignment: "atv05"
owner:
  username: "Japaishii"
  id: 134721783
  accepted_at: "2026-09-16T22:22:05Z"
  jidoahdouawhdoiuawhduioahduioadnioadhuiawdhioadnpioaw: "oi sumida"